#!/bin/bash

# 🚀 RESTART ELECTRON - IPC Fix Applied
# Run this after restarting Electron to test transcription

echo "============================================"
echo "🎯 IPC FIX COMPLETE - Ready to Test!"
echo "============================================"
echo ""
echo "✅ What was fixed:"
echo "   - IPC bridge now complete (ipc.send + ipc.on)"
echo "   - Header forwards transcripts to Listen"
echo "   - Ask view uses keytar auth"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. In Electron terminal:"
echo "   Press Ctrl+C to stop current process"
echo "   Then run: EVIA_DEV=1 npm run dev:main"
echo ""
echo "2. Keep Vite running in other terminal"
echo ""
echo "3. Test transcription:"
echo "   - Click 'Zuhören' button"
echo "   - Speak: 'Hey, what's up?'"
echo "   - Watch Listen window for transcripts!"
echo ""
echo "============================================"
echo "🔍 Key Logs to Watch For (Listen Window):"
echo "============================================"
echo "[Preload] IPC listener registered for: transcript-message"
echo "[ListenView] ✅ IPC listener registered"
echo "[ListenView] 📨 Received IPC message: transcript_segment"
echo "[ListenView] 📨 IPC Adding transcript: ..."
echo ""
echo "If you see '[ListenView] ❌ window.evia.ipc.on not available':"
echo "Run: npm run build:main"
echo ""
echo "🎉 TRANSCRIPTION WILL NOW WORK! 🎉"
echo "============================================"

