// Every microphone row that is really the far end must disappear, whenever the
// evidence arrives - not only if it happened to arrive first.
//
// Text verbatim from the 2026-08-09 session. The user said two short sentences
// and let a video play; almost the entire mic side was the video.
//
// The check this replaces required exact equality or full containment. The two
// sockets transcribe different words, so it matched once in a whole session.

const assert = require('node:assert/strict')
const test = require('node:test')

const {
  isBledFromFarEnd,
  longestSharedWordRun,
  dropBledMicRows,
  farEndTextOf,
  BLED_MIN_RUN_WORDS,
} = require('../dist/main/transcript-order.js')

const SYSTEM = [
  'Build their businesses, they have better ratings in some cases than The United States',
  "Yeah. Kinda makes sense. Yeah. The other thing that I think is important is",
  "that we're underestimating and miscounting some of the actual",
  "actual productivity gains that are underway. When you look at what's happening on the energy",
  'side, California published that more than 50% of all of its energy was',
  'generated by solar. New Mexico just published solar and batteries.',
].join(' ')

// Real mic rows from the same session - all of them the video, not the user.
const BLED = [
  'is they have better ratings in some cases than The United States',
  "Kinda makes sense. Yeah. The other thing that I think is important is",
  "I do think that we're underestimating and miscounting some of the actual",
  "some of the actual productivity gains that are underway. When you look",
  "When you look at what's happening on the energy side, California published",
]

// What the user actually said.
const GENUINE = [
  'Hey, David. How are you?',
  'Uh, still there.',
  'So does that change how you think about your own energy exposure at all',
  'Right, and what would that mean for the timeline you mentioned earlier',
]

const row = (speaker, text, extra = {}) => ({
  speaker, text, isFinal: true, isPartial: false, ...extra,
})

test('bled rows share long runs, genuine rows do not', () => {
  const bled = BLED.map((t) => longestSharedWordRun(t, SYSTEM))
  const genuine = GENUINE.map((t) => longestSharedWordRun(t, SYSTEM))
  assert.ok(Math.min(...bled) >= BLED_MIN_RUN_WORDS, `bled runs ${bled}`)
  assert.ok(Math.max(...genuine) < BLED_MIN_RUN_WORDS, `genuine runs ${genuine}`)
})

for (const text of BLED) {
  test(`bled row is detected: ${text.slice(0, 40)}`, () => {
    assert.equal(isBledFromFarEnd(text, SYSTEM), true)
  })
}

for (const text of GENUINE) {
  test(`genuine row survives: ${text.slice(0, 40)}`, () => {
    assert.equal(isBledFromFarEnd(text, SYSTEM), false)
  })
}

// ── the four gaps reported from the session ──────────────────────────────

test('GAP 1: partial mic rows are removed, not only finals', () => {
  const rows = [
    row(0, SYSTEM),
    row(1, BLED[0], { isFinal: false, isPartial: true }),
  ]
  assert.equal(dropBledMicRows(rows, farEndTextOf(rows)).length, 1)
})

test('GAP 2: a row that accumulated far-end text is removed', () => {
  // Accumulating bubbles grow; the check must apply to whatever they hold now.
  const growing = "I do think that we're underestimating and miscounting some of the actual"
  const rows = [row(0, SYSTEM), row(1, growing, { isFinal: false, isPartial: true })]
  assert.equal(dropBledMicRows(rows, farEndTextOf(rows)).length, 1)
})

test('GAP 3: rows displayed before any far-end text are removed once it arrives', () => {
  // Session start: the mic row is judged when no far-end text exists at all.
  let rows = [row(1, BLED[1])]
  assert.equal(dropBledMicRows(rows, farEndTextOf(rows)).length, 1, 'nothing to compare yet')
  rows = [...rows, row(0, SYSTEM)]
  const swept = dropBledMicRows(rows, farEndTextOf(rows))
  assert.equal(swept.length, 1)
  assert.equal(swept[0].speaker, 0, 'the mic row must be gone once evidence exists')
})

test('GAP 4: old rows are still removed - no time gate', () => {
  const rows = [
    row(1, BLED[2], { timestamp: 1, audioStartMs: 1 }),   // ancient
    row(0, SYSTEM, { timestamp: 9_999_999, audioStartMs: 9_999_999 }),
  ]
  assert.equal(dropBledMicRows(rows, farEndTextOf(rows)).length, 1)
})

test('the whole session collapses to the far end plus what the user said', () => {
  const rows = [
    ...GENUINE.map((t) => row(1, t)),
    ...BLED.map((t) => row(1, t)),
    row(0, SYSTEM),
  ]
  const swept = dropBledMicRows(rows, farEndTextOf(rows))
  const micLeft = swept.filter((r) => r.speaker === 1).map((r) => r.text)
  assert.deepEqual(micLeft, GENUINE, 'exactly the user speech, nothing else')
})

test('system rows are never removed', () => {
  const rows = [row(0, SYSTEM), row(0, BLED[0])]
  assert.equal(dropBledMicRows(rows, farEndTextOf(rows)).length, 2)
})

test('short mic rows are never judged this way', () => {
  assert.equal(isBledFromFarEnd('better ratings in some', SYSTEM), false)
})

test('an empty far end removes nothing', () => {
  const rows = BLED.map((t) => row(1, t))
  assert.equal(dropBledMicRows(rows, '').length, rows.length)
})
