/**
 * The seam: does what the backend SENDS satisfy what the desktop ACCEPTS?
 *
 * Nothing tested this. The desktop's adapter is the single gate deciding
 * whether a transcript row is ever shown, and it lived inside a React
 * component where it could not be imported. The backend's serializer lived in
 * websocket.py. Both sides had green suites on 2026-08-13 while the backend
 * emitted and the desktop rejected 100% of segments, and the Listen view
 * reported "Total: 0" with transcript_segment messages visibly arriving.
 *
 * The fixture is not hand-written. It is generated by walking the REAL backend
 * mapping - real ProviderCaptureLedger, real map_provider_result_timing, real
 * _frontend_timed_words - via
 *
 *     backend/scripts/emit_transcript_contract_fixture.py
 *
 * so this test fails if either side of the contract moves. It deliberately
 * includes the zero-width words ("Ja", "Und") that used to discard an entire
 * utterance, and a partial that is later superseded by its final.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { adaptServerTranscriptEvent } = require('../dist/main/realtime-transcript-adapter.js');
const {
  createRealtimeTranscriptState,
  applyRealtimeTranscriptEvent,
  projectRealtimeTranscriptState,
} = require('../dist/main/realtime-transcript-state.js');

const fixture = JSON.parse(fs.readFileSync(
  path.join(__dirname, 'fixtures/backend-transcript-contract.json'),
  'utf8',
));

test('the fixture really came from the backend, not from this test', () => {
  assert.ok(fixture.messages.length > 0, 'no messages in fixture');
  assert.match(fixture.note, /emit_transcript_contract_fixture\.py/);
  // The case that discarded whole utterances must still be represented, or the
  // fixture has quietly stopped covering the bug it exists for.
  const zeroWidth = fixture.messages
    .flatMap((message) => message.data.words)
    .filter((word) => word.capture_start_ms === word.capture_end_ms);
  assert.ok(zeroWidth.length > 0, 'fixture no longer contains a zero-width word');
});

test('every backend payload is ACCEPTED by the desktop adapter', () => {
  for (const message of fixture.messages) {
    const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
    assert.equal(
      adapted.reason,
      null,
      `backend sent ${message.data.source} "${message.data.text}" and the desktop rejected it: ${adapted.reason}`,
    );
    assert.ok(adapted.event, 'accepted but produced no event');
  }
});

test('every word survives with a usable capture clock', () => {
  for (const message of fixture.messages) {
    const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
    const spoken = message.data.words.map((word) => word.text).join(' ');
    assert.equal(
      adapted.event.words.length,
      message.data.words.length,
      `words were dropped from "${spoken}"`,
    );
    for (const word of adapted.event.words) {
      assert.ok(Number.isFinite(word.startMs) && Number.isFinite(word.endMs));
      assert.ok(word.startMs <= word.endMs);
    }
  }
});

test('the full exchange renders as the expected dialogue', () => {
  // End to end: backend payload -> real adapter -> real reducer -> projection.
  let state = createRealtimeTranscriptState();
  for (const message of fixture.messages) {
    const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
    assert.equal(adapted.reason, null, `rejected: ${adapted.reason}`);
    const transition = applyRealtimeTranscriptEvent(state, adapted.event);
    assert.ok(
      transition.accepted,
      `reducer refused ${message.data.source} "${message.data.text}": ${transition.reason}`,
    );
    state = transition.state;
  }

  const rows = projectRealtimeTranscriptState(state).visibleRows
    .map((row) => ({ source: row.source, text: row.text }));
  assert.deepEqual(rows, fixture.expectedRows);
});

test('a partial is replaced by its final rather than duplicated', () => {
  // u-mic-2 arrives twice: partial then final. Two rows would mean the rep sees
  // their own sentence twice mid-call.
  let state = createRealtimeTranscriptState();
  for (const message of fixture.messages) {
    const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
    state = applyRealtimeTranscriptEvent(state, adapted.event).state;
  }
  const rows = projectRealtimeTranscriptState(state).visibleRows;
  const texts = rows.map((row) => row.text);
  assert.equal(new Set(texts).size, texts.length, `duplicated rows: ${texts.join(' | ')}`);
});

test('both speakers are present and attributed correctly', () => {
  // A transcript that silently loses one side is the failure that started all
  // of this, and it looks healthy unless someone counts.
  let state = createRealtimeTranscriptState();
  for (const message of fixture.messages) {
    const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
    state = applyRealtimeTranscriptEvent(state, adapted.event).state;
  }
  const rows = projectRealtimeTranscriptState(state).visibleRows;
  const mic = rows.filter((row) => row.source === 'mic');
  const system = rows.filter((row) => row.source === 'system');
  assert.ok(mic.length > 0, 'no microphone rows - the rep is missing from their own call');
  assert.ok(system.length > 0, 'no system rows - the prospect is missing');
});

test('a missing per-word clock is still refused', () => {
  // The guarantee that makes the strictness worth having: an event whose words
  // carry no capture time cannot be ordered against the other stream.
  const message = JSON.parse(JSON.stringify(fixture.messages[0]));
  delete message.data.words[0].capture_start_ms;
  const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
  assert.equal(adapted.reason, 'unmapped-word-clock');
});

test('an unprovable clock domain is still refused', () => {
  const message = JSON.parse(JSON.stringify(fixture.messages[0]));
  message.data.clock_domain_valid = false;
  const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
  assert.equal(adapted.reason, 'invalid-clock-domain');
});

test('a source-tag mismatch is still refused', () => {
  const message = JSON.parse(JSON.stringify(fixture.messages[0]));
  message._source = message.data.source === 'mic' ? 'system' : 'mic';
  const adapted = adaptServerTranscriptEvent(message, fixture.chatId);
  assert.equal(adapted.reason, 'source-mismatch');
});
