const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = (...parts) =>
  fs.readFileSync(path.join(root, ...parts), 'utf8').replace(/\r\n/g, '\n')

test('the Windows release builds one x64 and ARM64 NSIS installer', () => {
  const pkg = JSON.parse(read('package.json'))
  const command = pkg.scripts['build:release:win']
  assert.match(command, /build:native:audio:win/)
  assert.match(command, /build:native:glass/)
  assert.match(command, /electron-builder --win nsis --x64 --arm64 --publish never/)

  const builder = read('electron-builder.yml')
  assert.match(builder, /target: nsis\n\s+arch:\n\s+- x64\n\s+- arm64/)
  assert.match(builder, /buildUniversalInstaller: true/)
  assert.match(builder, /artifactName: "Taylos\.\$\{ext\}"/)
})

test('the packaged WASAPI fallback selects a native helper at runtime', () => {
  const service = read('src', 'main', 'system-audio-windows-service.ts')
  const build = read('scripts', 'build-windows-audio-helper.js')
  const builder = read('electron-builder.yml')

  assert.match(service, /process\.arch === 'arm64' \? 'arm64' : 'x64'/)
  assert.match(service, /'windows-audio', architecture, 'WASAPILoopback\.exe'/)
  assert.match(build, /name: 'x64'.*machine: 0x8664/)
  assert.match(build, /name: 'arm64'.*machine: 0xaa64/)
  assert.match(builder, /from: "native\/windows\/build"/)
})

test('the self-hosted workflow never queries the privileged runner-list endpoint', () => {
  const workflow = read('.github', 'workflows', 'release-windows-self-hosted.yml')
  const desktopWorkflow = read('.github', 'workflows', 'release-desktop.yml')
  assert.doesNotMatch(workflow, /actions\/runners/)
  assert.doesNotMatch(workflow, /push:\n\s+tags:/)
  assert.match(workflow, /workflow_call:/)
  assert.match(workflow, /runs-on: \[self-hosted, windows-signing\]/)
  assert.match(workflow, /default: false\n\s+type: boolean/)
  assert.match(desktopWorkflow, /uses: \.\/\.github\/workflows\/release-windows-self-hosted\.yml/)
  assert.match(desktopWorkflow, /windows-build-sign-and-publish:[\s\S]*upload: true/)
})

test('SimplySign release execution fails closed outside an elevated session', () => {
  const release = read('scripts', 'release-windows-signed.ps1')
  const serialSigner = read('scripts', 'sign-windows-serial.js')
  const builder = read('electron-builder.yml')
  const launcher = read('scripts', 'run-release-windows-elevated.ps1')
  assert.match(release, /Assert-ElevatedSession/)
  assert.match(release, /tools\\node-v22\.12\.0-win-x64/)
  assert.match(release, /\$env:Path = "\$pinnedNode;\$env:Path"/)
  assert.match(release, /if \(\$Upload\)[\s\S]*GitHub CLI authentication is required for upload/)
  assert.match(release, /continuing the local non-upload build/)
  assert.match(release, /\$env:SIGNTOOL_PATH = \$signTool/)
  assert.match(builder, /sign: \.\/scripts\/sign-windows-serial\.js/)
  assert.match(serialSigner, /let signingQueue = Promise\.resolve\(\)/)
  assert.match(serialSigner, /signingQueue\.then\(\(\) => signOne\(configuration\)\)/)
  assert.match(serialSigner, /0x80090020/)
  assert.match(serialSigner, /http:\/\/time\.certum\.pl/)
  assert.match(serialSigner, /SIGNTOOL_PATH is required/)
  assert.match(release, /SimplySign private-key access requires an elevated interactive session/)
  assert.match(release, /judge native commands\n\s+# by their process exit code/)
  assert.match(release, /\$exitCode = \$LASTEXITCODE/)
  assert.match(release, /\$resolvedPath = \(Resolve-Path -LiteralPath \$Path\)\.Path/)
  assert.match(release, /ReadAllBytes\(\$resolvedPath\)/)
  assert.match(release, /Upload requires a clean working tree/)
  assert.match(release, /Upload requires HEAD .* to match .* commit/)
  assert.match(release, /Invoke-Checked "npm" @\("run", "test:transcript"\)/)
  assert.match(release, /"--draft"/)
  assert.match(release, /finalize-release-if-complete\.js/)
  assert.match(launcher, /Start-Process powershell\.exe -Verb RunAs/)
  assert.match(launcher, /Disable-ConsoleQuickEdit/)
  assert.match(launcher, /enableQuickEditMode = \[uint32\]0x0040/)
})

test('the elevated wrapper forwards release switches by name without piping the child script', () => {
  const launcher = read('scripts', 'run-release-windows-elevated.ps1')
  assert.match(launcher, /\$releaseArguments\s*=\s*@\{\}/)
  assert.match(launcher, /\$releaseArguments\.Upload\s*=\s*\$true/)
  assert.match(launcher, /\$releaseArguments\.SkipInstall\s*=\s*\$true/)
  assert.match(launcher, /\$releaseArguments\.VerifyOnly\s*=\s*\$true/)
  assert.doesNotMatch(launcher, /release-windows-signed\.ps1[^\n]*\*>\&1[^\n]*Tee-Object/)
})

test('Windows update metadata is explicit, stable-only, and preserves user data', () => {
  const builder = read('electron-builder.yml')
  const installer = read('build', 'installer.nsh')
  const main = read('src', 'main', 'main.ts')

  assert.match(builder, /publish:\n\s+provider: github\n\s+owner: EVIA-Production\n\s+repo: EVIA-Desktop/)
  assert.match(builder, /appId: com\.taylos\.app/)
  assert.match(builder, /publisherName:\n\s+- "Benedict Kroetz"/)
  assert.match(builder, /signExts:\n\s+- "\.node"/)
  assert.match(builder, /deleteAppDataOnUninstall: false/)
  assert.match(builder, /include: build\/installer\.nsh/)
  assert.match(installer, /taylosWaitForWritableInstallDirectory/)
  assert.match(installer, /taylosAssertInstallDirectoryEmpty/)
  assert.match(installer, /^!ifndef BUILD_UNINSTALLER/)
  assert.match(installer, /SetErrorLevel 2\n\s+Quit/)
  assert.match(installer, /!macro preInit/)
  assert.match(installer, /\$EXEFILE == "\$\{APP_EXECUTABLE_FILENAME\}"/)
  assert.match(installer, /Taylos-Setup\.exe/)
  assert.match(installer, /StdUtils\.GetAllParameters/)
  assert.match(installer, /WaitForSingleObject/)
  assert.match(installer, /Exec '\"\$R3\" \$R0 --taylos-bootstrap-parent=\$R1'/)
  assert.doesNotMatch(installer, /ExecWait[^\n]*taylos-bootstrap-parent/)
  assert.match(installer, /Delete \/REBOOTOK "\$EXEPATH"/)
  assert.match(installer, /RMDir \/REBOOTOK "\$EXEDIR"/)
  assert.match(main, /scheduleWindowsInstallerBootstrapCleanup/)
  assert.match(main, /taylos-installer-bootstrap/)
  assert.match(main, /fs\.promises\.unlink\(bootstrapPath\)/)
  assert.match(main, /autoUpdater\.allowPrerelease = false/)
  assert.match(main, /autoUpdater\.allowDowngrade = false/)
  assert.match(main, /autoUpdater\.checkForUpdates\(\)/)
  assert.match(main, /path\.join\(app\.getPath\('userData'\), 'updater-audit\.json'\)/)
})

test('the release verifier checks the packaged Windows glass bridge', () => {
  const release = read('scripts', 'release-windows-signed.ps1')
  assert.match(release, /function Reset-ReleaseOutput/)
  assert.match(release, /GetDirectoryName\(\$dist\) -ne \$repoRoot/)
  assert.match(release, /Remove-Item -LiteralPath \$dist -Recurse -Force/)
  assert.match(release, /resources\\native\\windows-liquid-glass\\prebuilds\\win32-/)
  assert.match(release, /Assert-PeArchitecture \$glassBridge \$payload\.Architecture/)
  assert.match(release, /Assert-SignedFile \$SignTool \$glassBridge \$ExpectedThumbprint/)
})

test('Mac dispatch checks runner presence without storing an Actions PAT', () => {
  const trigger = read('scripts', 'trigger-windows-release.sh')
  assert.match(trigger, /gh auth status/)
  assert.match(trigger, /actions\/runners/)
  assert.match(trigger, /windows-signing/)
  assert.match(trigger, /upload="false"/)
  assert.match(trigger, /previous_run_id=/)
  assert.match(trigger, /gh run watch "\$run_id" --repo "\$repo" --exit-status/)
  assert.doesNotMatch(trigger, /GH_TOKEN|GITHUB_TOKEN|PAT=/)
})

test('the Windows signing runner is interactive, elevated, and proves the HSM before accepting jobs', () => {
  const starter = read('scripts', 'start-windows-signing-runner.ps1')
  const task = read('scripts', 'configure-windows-signing-runner-task.ps1')

  assert.match(starter, /Test-IsAdministrator/)
  assert.match(starter, /Get-Process -Name SimplySignDesktop/)
  assert.match(starter, /signtool sign \/fd SHA256/)
  assert.match(starter, /signtool verify \/pa \/v/)
  assert.match(starter, /Get-AuthenticodeSignature/)
  assert.match(task, /-LogonType Interactive -RunLevel Highest/)
  assert.match(task, /ProgramData.*Taylos\\signing-runner/)
  assert.match(task, /function Protect-ElevatedPath/)
  assert.match(task, /SetAccessRuleProtection\(\$true, \$false\)/)
  assert.match(task, /S-1-5-32-544/)
  assert.match(task, /Assert-ElevatedPathProtection \$RunnerRoot/)
  assert.match(task, /ExecutablePath\.StartsWith/)
  assert.match(task, /Runner processes remained after the scheduled task stopped/)
  assert.match(task, /does not execute the protected launcher/)
  assert.doesNotMatch(task, /-File `"\$starterSource`"/)
  assert.doesNotMatch(task, /New-Service|sc\.exe|LogonType Service/)
})

test('the installer upgrade gate preserves profile state and exercises the public filename', () => {
  const upgrade = read('scripts', 'test-windows-installer-upgrade.ps1')

  assert.match(upgrade, /Split-Path -Leaf \$CandidatePath/)
  assert.match(upgrade, /"Taylos\.exe"/)
  assert.match(upgrade, /Get-FileHash -Algorithm SHA256/)
  assert.match(upgrade, /LastWriteTimeUtc/)
  assert.match(upgrade, /Get-AuthenticodeSignature/)
  assert.match(upgrade, /\/KEEP_APP_DATA/)
  assert.match(upgrade, /Upgrade Taylos \$previousVersion to \$candidateVersion/)
  assert.match(upgrade, /Repeat Taylos \$candidateVersion/)
})
