/**
 * The echo-cancellation gate.
 *
 *     node tools/aec-bench.cjs                 # gate the shipping canceller
 *     node tools/aec-bench.cjs --engine=speex  # the one it replaced
 *     node tools/aec-bench.cjs --engine=none   # sanity: the rig itself is honest
 *     node tools/aec-bench.cjs --wav           # also write audio to tools/aec-out/
 *
 * Nothing gets enabled in the app that has not passed this. Two rules earned
 * the hard way:
 *
 *   1. A canceller handed a SILENT reference has nothing to cancel and must
 *      return the microphone untouched. The Speex build failed this by 9dB and
 *      that single test, run on day one, would have saved a day of work.
 *   2. Results must DIFFER across echo delays. Identical numbers at 0, 60 and
 *      150ms mean the filter is not adapting to the reference at all - which is
 *      exactly what the Speex build showed at every filter length tried.
 *
 * The scenario is real speech (two voices, generated by `tools/make-speech.sh`)
 * through a synthetic but hardware-shaped room response, arranged in regions so
 * that echo and near end are never measured on the same material:
 *
 *     far only  |  near only  |  double talk
 *     0 ....11s      11..18s      18......29s
 *
 * Echo suppression is measured where only echo exists. Near-end damage is
 * measured where only the near end exists. Conflating them is how a canceller
 * that merely turns the rep down gets scored as if it were cancelling.
 */

const path = require('node:path');
const fs = require('node:fs');
const lab = require('./aec-lab.cjs');

process.setMaxListeners(0);

const RATE = 24_000;
const CHUNK = 2400;                    // 100ms, exactly what the pipeline hands over
const SPEECH_DIR = path.join(__dirname, 'aec-speech');
const OUT_DIR = path.join(__dirname, 'aec-out');

const args = process.argv.slice(2);
const argOf = (name, dflt) => {
  const hit = args.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : dflt;
};
const ENGINE = argOf('engine', 'aec3');
const WRITE_WAV = args.includes('--wav');

const fmt = (x, w = 5) => (x >= 0 ? '+' : '') + x.toFixed(1).padStart(w);
const pass = (ok) => (ok ? '\x1b[32mPASS\x1b[0m' : '\x1b[31mFAIL\x1b[0m');

// ─────────────────────────────────────────────────────────────────────────────
// Engines
// ─────────────────────────────────────────────────────────────────────────────

async function makeEngine(name) {
  if (name === 'none') {
    return {
      label: 'passthrough',
      process: (mic) => Float32Array.from(mic),
      dispose() {},
    };
  }

  if (name === 'speex') {
    const createAec = require('../src/renderer/aec/aec.js');
    const { requiredFilterSamples } = require('../dist/main/aec-reference.js');
    const M = await createAec();
    const FRAME = 160;
    const ptr = M._AecNew(FRAME, requiredFilterSamples(), RATE, 0);
    if (!ptr) throw new Error('AecNew failed');
    const cancel = M.cwrap('AecCancelEcho', null, ['number', 'number', 'number', 'number', 'number']);
    const micPtr = M._malloc(FRAME * 2);
    const refPtr = M._malloc(FRAME * 2);
    const outPtr = M._malloc(FRAME * 2);
    const put = (src, off, p) => {
      const h = new Int16Array(M.HEAP16.buffer, p, FRAME);
      for (let i = 0; i < FRAME; i += 1) {
        h[i] = Math.max(-32768, Math.min(32767, Math.round((src[off + i] || 0) * 32767)));
      }
    };
    return {
      label: `speex (${requiredFilterSamples()} taps)`,
      process(mic, ref) {
        const out = new Float32Array(mic.length);
        for (let off = 0; off + FRAME <= mic.length; off += FRAME) {
          put(mic, off, micPtr); put(ref, off, refPtr);
          cancel(ptr, micPtr, refPtr, outPtr, FRAME);
          const h = new Int16Array(M.HEAP16.buffer, outPtr, FRAME);
          for (let i = 0; i < FRAME; i += 1) out[off + i] = h[i] / 32768;
        }
        return out;
      },
      dispose() { M._AecDestroy(ptr); },
    };
  }

  if (name === 'aec3') {
    const { Aec3Canceller } = require('../dist/main/aec3-canceller.js');
    const canceller = await Aec3Canceller.create();
    return {
      label: `WebRTC AEC3 @${canceller.internalRate}Hz`,
      process: (mic, ref) => canceller.process(mic, ref),
      dispose: () => canceller.dispose(),
    };
  }

  throw new Error(`unknown engine: ${name}`);
}

/** Drive an engine over a whole stream in the pipeline's 100ms chunks. */
function runStream(engine, mic, ref) {
  const n = Math.floor(Math.min(mic.length, ref.length) / CHUNK) * CHUNK;
  const out = new Float32Array(n);
  for (let off = 0; off < n; off += CHUNK) {
    out.set(engine.process(mic.subarray(off, off + CHUNK), ref.subarray(off, off + CHUNK)), off);
  }
  return { out, n };
}

/** A fresh engine per scenario: adaptation state must never leak between tests. */
async function fresh(fn) {
  const engine = await makeEngine(ENGINE);
  try {
    return await fn(engine);
  } finally {
    engine.dispose();
  }
}

/**
 * The same audio through the same canceller with NOTHING to cancel.
 *
 * This is the honest baseline for "what did cancellation cost". It is not the
 * raw input: AEC3 resamples 24k -> 48k -> 24k and that round trip alone costs
 * about half a dB, which charged to the canceller would look like damage. The
 * port's own `pre` option would give the same thing for free and is unusable -
 * it runs a stateful resampler twice per frame and wrecks the real output by
 * 14dB. See the header of `src/main/aec3-canceller.ts`.
 */
async function idleOf(signal) {
  const silence = new Float32Array(signal.length);
  const { out } = await fresh((e) => runStream(e, signal, silence));
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// Material
// ─────────────────────────────────────────────────────────────────────────────

function loadSpeech() {
  const farPath = path.join(SPEECH_DIR, 'far.wav');
  const nearPath = path.join(SPEECH_DIR, 'near.wav');
  if (!fs.existsSync(farPath) || !fs.existsSync(nearPath)) {
    throw new Error(
      `missing test speech in ${SPEECH_DIR}\n` +
      `  generate it with:  bash tools/make-speech.sh`,
    );
  }
  const far = lab.readWav(farPath);
  const near = lab.readWav(nearPath);
  if (far.rate !== RATE || near.rate !== RATE) {
    throw new Error(`test speech must be ${RATE}Hz, got far=${far.rate} near=${near.rate}`);
  }
  return { far: far.samples, near: near.samples };
}

const S = (sec) => Math.round(sec * RATE);

/**
 * The regioned scenario.
 *
 * `refSkewSamples` models an alignment error: positive means the reference we
 * hand the canceller comes from LATER than the microphone window (delta > 0 in
 * aec-reference.ts's convention). Negative means earlier, and once it exceeds
 * the acoustic delay the echo precedes the canceller's whole history and no
 * filter of any length can model it. That cliff is a live risk on the macOS
 * path, so the bench maps it rather than assuming it away.
 */
function buildScenario(speech, opts = {}) {
  const {
    delayMs = 60, erlDb = 19, drive = 1, driftPpm = 0,
    refSkewSamples = 0, seed = 4242,
  } = opts;

  const total = S(29);
  const render = new Float32Array(total);   // what the speakers play
  const near = new Float32Array(total);     // what the rep says

  const farA = speech.far.subarray(0, S(11));
  const farB = speech.far.subarray(S(11));
  render.set(farA, 0);
  render.set(farB.subarray(0, total - S(18)), S(18));

  const nearA = speech.near.subarray(0, S(7));
  const nearB = speech.near.subarray(S(7));
  near.set(nearA, S(11));
  near.set(nearB.subarray(0, total - S(18)), S(18));

  // The speaker distorts before the room ever sees the signal.
  const played = lab.saturate(render, drive);

  const ir = lab.scaleToErl(lab.makeRoomImpulse({ rate: RATE, delayMs, seed }), played, erlDb);
  let echo = lab.convolve(played, ir);

  // Clock drift: the echo is captured on the mic's clock, the reference on the
  // helper's. If they differ the echo slides against the reference over time.
  if (driftPpm !== 0) {
    const drifted = lab.resampleRatio(echo, 1 + driftPpm / 1e6);
    echo = new Float32Array(total);
    echo.set(drifted.subarray(0, Math.min(drifted.length, total)));
  }

  // The reference actually handed to the canceller, with any alignment error.
  const reference = new Float32Array(total);
  for (let i = 0; i < total; i += 1) {
    const src = i + refSkewSamples;
    reference[i] = src >= 0 && src < total ? render[src] : 0;
  }

  return { render, reference, near, echo, ir, total };
}

const REGIONS = {
  converge: [S(0.5), S(3)],     // far only, filter still adapting
  farOnly: [S(5), S(11)],       // far only, converged
  nearOnly: [S(12), S(18)],     // near only, 1s guard after the far end stops
  doubleTalk: [S(19), S(26)],   // both, 1s guard after the far end restarts
};

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

const results = { gates: [], notes: [] };
const gate = (name, ok, detail) => {
  results.gates.push({ name, ok, detail });
  console.log(`  ${pass(ok)}  ${name.padEnd(46)} ${detail}`);
};

async function testSilentReference(speech) {
  console.log('\n\x1b[1m1. SILENT REFERENCE\x1b[0m  — nothing to cancel, so nothing may change');

  // Band-limited noise, not white: the pipeline carries speech, and white noise
  // to Nyquist mostly measures the resampler's anti-alias filter rather than
  // anything the canceller did.
  const rand = lab.makeRandom(7);
  const noise = lab.lowpass(
    Float32Array.from({ length: S(12) }, () => (rand() * 2 - 1) * 0.2), RATE, 8000,
  );

  const cases = [
    ['real speech', speech.near.subarray(0, S(12))],
    ['noise (band-limited)', noise],
    ['tone 210Hz', Float32Array.from({ length: S(12) }, (_, i) => 0.2 * Math.sin((2 * Math.PI * 210 * i) / RATE))],
  ];

  for (const [label, mic] of cases) {
    const silence = new Float32Array(mic.length);
    const { out, n } = await fresh((e) => runStream(e, mic, silence));
    const from = Math.floor(n / 3);
    const change = lab.levelDb(out, from, n) - lab.levelDb(mic, from, n);
    gate(`silent reference / ${label}`, Math.abs(change) <= 1, `${fmt(change)} dB vs raw mic`);
  }
}

async function testDelaySweep(speech) {
  console.log('\n\x1b[1m2. ECHO ONLY, DELAY SWEEP\x1b[0m  — echo with no near end, so ERLE is exact');

  const erles = [];
  for (const delayMs of [0, 30, 60, 150, 300]) {
    const sc = buildScenario(speech, { delayMs });
    const { out, n } = await fresh((e) => runStream(e, sc.echo, sc.reference));
    const idle = await idleOf(sc.echo);
    const [a, b] = REGIONS.farOnly;
    const erle = lab.levelDb(idle, a, Math.min(b, n)) - lab.levelDb(out, a, Math.min(b, n));
    erles.push({ delayMs, erle });
    const label = delayMs === 60 ? ' \x1b[2m<- measured hardware\x1b[0m' : '';
    console.log(`     ${String(delayMs).padStart(3)}ms   ERLE ${fmt(erle)} dB${label}`);
  }

  const at60 = erles.find((e) => e.delayMs === 60).erle;
  gate('ERLE at the measured 60ms path >= 10dB', at60 >= 10, `${fmt(at60)} dB`);

  const spread = Math.max(...erles.map((e) => e.erle)) - Math.min(...erles.map((e) => e.erle));
  gate('results differ across delays (filter adapts)', spread >= 1,
    `spread ${spread.toFixed(1)} dB across 0-300ms`);
}

async function testRegions(speech) {
  console.log('\n\x1b[1m3. FULL SCENARIO\x1b[0m  — real speech, 60ms path, 19dB ERL');

  const sc = buildScenario(speech);
  const mic = Float32Array.from(sc.near, (v, i) => v + sc.echo[i]);

  // Three runs over identical reference. Echo and near end are separable only
  // if they are measured on material that contains one and not the other.
  const echoRun = await fresh((e) => runStream(e, sc.echo, sc.reference));
  const nearRun = await fresh((e) => runStream(e, sc.near, sc.reference));
  const bothRun = await fresh((e) => runStream(e, mic, sc.reference));
  const echoIdle = await idleOf(sc.echo);
  const nearIdle = await idleOf(sc.near);
  const n = bothRun.n;

  const region = (name) => {
    const [a, b] = REGIONS[name];
    return [a, Math.min(b, n)];
  };

  const [cf, ct] = region('converge');
  const [ff, ft] = region('farOnly');
  const erleEarly = lab.levelDb(echoIdle, cf, ct) - lab.levelDb(echoRun.out, cf, ct);
  const erleConv = lab.levelDb(echoIdle, ff, ft) - lab.levelDb(echoRun.out, ff, ft);
  console.log(`     echo suppression   0.5-3s ${fmt(erleEarly)} dB   5-11s ${fmt(erleConv)} dB`);

  // Echo suppression measured on echo-only material is flattering during double
  // talk: with no near end to protect, AEC3's residual suppressor can gate the
  // band shut, and it reports 60dB. What actually reaches Deepgram is the
  // difference between processing (near + echo) and processing near alone, with
  // the same reference in both. Not exact - the suppressor is nonlinear, so the
  // two runs do not superpose - but it is the honest direction, and it is the
  // number the transcript depends on.
  const [df, dt] = region('doubleTalk');
  const erleGated = lab.levelDb(echoIdle, df, dt) - lab.levelDb(echoRun.out, df, dt);
  const echoProj = lab.projectGainDb(bothRun.out, sc.echo, df, dt);
  const nearProj = lab.projectGainDb(bothRun.out, sc.near, df, dt);
  const erleDouble = -echoProj.gainDb;
  console.log(`     echo suppression during double talk        ${fmt(erleDouble)} dB` +
    `   \x1b[2m(${fmt(erleGated)} dB measured on echo-only material)\x1b[0m`);
  console.log(`     rep's voice kept during double talk        ${fmt(nearProj.gainDb)} dB` +
    `   \x1b[2m(correlation ${nearProj.corr.toFixed(3)})\x1b[0m`);

  // Near-end damage with the reference ACTIVE. Stricter than the silent-
  // reference test and the one that matters: this is the rep talking while the
  // prospect's audio is playing, and a canceller that eats the rep here is
  // worse than no canceller at all. Losing the rep's words is the single worst
  // outcome in this product.
  const [nf, nt] = region('nearOnly');
  const nearQuiet = lab.levelDb(nearRun.out, nf, nt) - lab.levelDb(nearIdle, nf, nt);
  const nearDouble = lab.levelDb(nearRun.out, df, dt) - lab.levelDb(nearIdle, df, dt);
  console.log(`     rep's voice kept   far silent ${fmt(nearQuiet)} dB   far playing ${fmt(nearDouble)} dB`);

  gate('rep kept while far end plays (>= -1dB)', nearDouble >= -1, `${fmt(nearDouble)} dB`);
  gate('rep kept after far end stops (>= -1dB)', nearQuiet >= -1, `${fmt(nearQuiet)} dB`);
  gate('rep kept THROUGH double talk (>= -3dB)', nearProj.gainDb >= -3, `${fmt(nearProj.gainDb)} dB`);
  gate('echo suppressed during double talk >= 10dB', erleDouble >= 10, `${fmt(erleDouble)} dB`);

  // How loud is the leftover echo compared with the rep, in the mix Deepgram
  // actually receives? This is the number that decides whether the far end
  // gets transcribed a second time.
  const before = lab.levelDb(sc.echo, df, dt) - lab.levelDb(sc.near, df, dt);
  const after = before + echoProj.gainDb - nearProj.gainDb;
  console.log(`     echo-to-rep ratio  before ${fmt(before)} dB   after ${fmt(after)} dB` +
    `   \x1b[2m<- what Deepgram receives\x1b[0m`);

  if (WRITE_WAV) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
    lab.writeWav(path.join(OUT_DIR, 'mic-raw.wav'), mic.subarray(0, n), RATE);
    lab.writeWav(path.join(OUT_DIR, `mic-cancelled-${ENGINE}.wav`), bothRun.out, RATE);
    lab.writeWav(path.join(OUT_DIR, 'near-truth.wav'), sc.near.subarray(0, n), RATE);
    lab.writeWav(path.join(OUT_DIR, 'render.wav'), sc.render.subarray(0, n), RATE);
    console.log(`     wrote audio to ${path.relative(process.cwd(), OUT_DIR)}/`);
  }

  return { sc, mic, n };
}

async function testAlignment(speech) {
  console.log('\n\x1b[1m4. ALIGNMENT TOLERANCE\x1b[0m  — how wrong can the reference timing be?');
  console.log('     delta < 0 = reference older than the mic window. Past -60ms the echo');
  console.log('     precedes the canceller\'s history and no filter can reach it.');

  for (const skewMs of [100, 40, 0, -40, -60, -120, -250]) {
    const sc = buildScenario(speech, { refSkewSamples: Math.round((skewMs / 1000) * RATE) });
    const { out, n } = await fresh((e) => runStream(e, sc.echo, sc.reference));
    const idle = await idleOf(sc.echo);
    const [a, b] = REGIONS.farOnly;
    const erle = lab.levelDb(idle, a, Math.min(b, n)) - lab.levelDb(out, a, Math.min(b, n));
    const verdict = erle >= 10 ? 'ok' : erle >= 3 ? 'degraded' : 'dead';
    console.log(`     delta ${String(skewMs).padStart(5)}ms   ERLE ${fmt(erle)} dB   ${verdict}`);
  }
}

async function testRobustness(speech) {
  console.log('\n\x1b[1m5. ROBUSTNESS\x1b[0m  — the things production has that a bench usually does not');

  const scenarios = [
    ['clean', {}],
    ['speaker overdriven (nonlinear)', { drive: 4 }],
    ['clock drift  +50 ppm', { driftPpm: 50 }],
    ['clock drift +200 ppm', { driftPpm: 200 }],
    ['clock drift +1000 ppm', { driftPpm: 1000 }],
    ['quiet echo (ERL 30dB)', { erlDb: 30 }],
    ['loud echo (ERL 6dB)', { erlDb: 6 }],
  ];

  for (const [label, opts] of scenarios) {
    const sc = buildScenario(speech, opts);
    const { out, n } = await fresh((e) => runStream(e, sc.echo, sc.reference));
    const idle = await idleOf(sc.echo);
    // Late window: drift only bites after it has had time to accumulate.
    const a = S(20); const b = Math.min(S(26), n);
    const erle = lab.levelDb(idle, a, b) - lab.levelDb(out, a, b);
    console.log(`     ${label.padEnd(32)} ERLE ${fmt(erle)} dB`);
  }
}

async function testCost(speech) {
  console.log('\n\x1b[1m6. COST\x1b[0m  — this runs inside a 100ms audio callback');
  const sc = buildScenario(speech);
  const engine = await makeEngine(ENGINE);
  const started = process.hrtime.bigint();
  runStream(engine, sc.echo, sc.reference);
  const elapsedMs = Number(process.hrtime.bigint() - started) / 1e6;
  engine.dispose();
  const audioMs = (sc.total / RATE) * 1000;
  const rtf = elapsedMs / audioMs;
  console.log(`     ${elapsedMs.toFixed(0)}ms of CPU for ${(audioMs / 1000).toFixed(0)}s of audio ` +
    `= ${(rtf * 100).toFixed(1)}% of one core (${(rtf * 100).toFixed(1)}ms per 100ms chunk)`);
  gate('cheap enough for the audio callback (<20% core)', rtf < 0.2, `${(rtf * 100).toFixed(1)}%`);
}

/**
 * Is the simulated path a fair stand-in for the real one?
 *
 * If the rig's echo were far more cancellable than the hardware's, every number
 * below would be optimistic and the gate would be worthless. Compare its bulk
 * delay, echo return loss and coherence against what was measured on the actual
 * MacBook: 60.3ms, 19.0dB, 0.976.
 */
function reportPathPhysics(speech) {
  const sc = buildScenario(speech);
  const [a, b] = REGIONS.farOnly;
  const render = sc.render.subarray(a, b);
  const echo = sc.echo.subarray(a, b);
  const lag = lab.bestLag(render, echo, S(0.4));
  const coh = lab.coherence(render, echo, RATE, { lag });
  const ceiling = -10 * Math.log10(Math.max(1 - coh, 1e-6));
  const erl = lab.levelDb(sc.render, a, b) - lab.levelDb(sc.echo, a, b);
  console.log(`\n\x1b[2mrig check: simulated path delay ${((lag / RATE) * 1000).toFixed(1)}ms, ` +
    `ERL ${erl.toFixed(1)}dB, coherence ${coh.toFixed(3)} (linear ceiling ${ceiling.toFixed(1)}dB).`);
  console.log(`           hardware measured    delay 60.3ms, ERL 19.0dB, coherence 0.976 (ceiling 16.1dB).\x1b[0m`);
}

// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const speech = loadSpeech();
  const engine = await makeEngine(ENGINE);
  console.log(`\n\x1b[1mAEC GATE\x1b[0m  engine=${ENGINE}  (${engine.label})  rate=${RATE}Hz  chunk=${CHUNK}`);
  engine.dispose();

  reportPathPhysics(speech);

  await testSilentReference(speech);
  await testDelaySweep(speech);
  await testRegions(speech);
  await testAlignment(speech);
  await testRobustness(speech);
  await testCost(speech);

  const failed = results.gates.filter((g) => !g.ok);
  console.log(`\n${'─'.repeat(78)}`);
  if (failed.length === 0) {
    console.log(`\x1b[32mALL ${results.gates.length} GATES PASS\x1b[0m — ${ENGINE} is safe to enable.`);
  } else {
    console.log(`\x1b[31m${failed.length} of ${results.gates.length} GATES FAIL\x1b[0m — do not enable ${ENGINE}.`);
    for (const f of failed) console.log(`  - ${f.name}: ${f.detail}`);
  }
  process.exit(failed.length === 0 ? 0 : 1);
})().catch((e) => { console.error('\nBENCH FAILED:', e); process.exit(2); });
